# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.3
    - 127.0.0.1
    - ::1

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.generac: debug
